apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: control-tower
  namespace: gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: control-tower
  minReplicas: 10
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
